name: Node.js CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: SSH into server and restart Docker container

       run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/ssh_key

          chmod 600 ~/ssh_key
          mkdir -p ~/.ssh
          echo "${{ secrets.KNOWN_HOSTS }}" > ~/.ssh/known_hosts

          ssh -o StrictHostKeyChecking=no -i ~/ssh_key ubuntu@13.51.201.242 \
            "cd AIhelper ||git pull  https://github.com/SowreeshUndru/HelperAI.git || cd HelperAI || npm install || npm run webhook || npm run dev "

            
        
      
