name: Node.js CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: SSH into server and deploy
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/ssh_key
          chmod 600 ~/ssh_key
          mkdir -p ~/.ssh
          echo "${{ secrets.KNOWN_HOSTS }}" > ~/.ssh/known_hosts

          ssh -o StrictHostKeyChecking=no -i ~/ssh_key ubuntu@13.51.201.242 << 'EOF'
            cd ~/AIhelper/HelperAI || 
            git pull origin main
            npm install
             || npm run webook || npm run dev
          EOF
